
import 'package:jadecandyv1/models/Gallery/model/CandyPostModel.dart';

import '../../../CAT/Media/MediaCAT.dart';
import '../model/candyLineListModel.dart';

final CandyLineListModel CandyLineData =
  CandyLineListModel(
      lineModelName: 'DummyData',
      lineModelLogo: '',

    models_: <CandyPost> [
      CandyPost(
        name:  MediaCAT.nameDefaultValue,
        urlImage: MediaCAT.addressDefaultValue,
        url: MediaCAT.addressDefaultValue,
        isWeb: false,
        localName: MediaCAT.nameDefaultValue,
        isAvailable: false,
        collection: MediaCAT.adventurerGirlPlus,
        releaseDate: MediaCAT.dateDefaultValue,
        model: MediaCAT.modelDefaultValue,
        webUrl: MediaCAT.webAddressDefaultValue,
        previewUrl:MediaCAT.addressDefaultValue,
        previewName:  MediaCAT.nameDefaultValue,
        index_: 0,
        description: MediaCAT.descriptionDefaultValue,
        IGTag: '${MediaCAT.urlIG}C5tmQ7dx0C5${MediaCAT.apiIGOPS}',
      ),
      CandyPost(
        name:  MediaCAT.nameDefaultValue,
        urlImage: MediaCAT.addressDefaultValue,
        url: MediaCAT.addressDefaultValue,
        isWeb: false,
        localName: MediaCAT.nameDefaultValue,
        isAvailable: false,
        collection: MediaCAT.adventurerGirlPlus,
        releaseDate: MediaCAT.dateDefaultValue,
        model: MediaCAT.modelDefaultValue,
        webUrl: MediaCAT.webAddressDefaultValue,
        previewUrl:MediaCAT.addressDefaultValue,
        previewName:  MediaCAT.nameDefaultValue,
        index_: 1,
        description: MediaCAT.descriptionDefaultValue,
        IGTag: '${MediaCAT.urlIG}C5OtieuRZ4e${MediaCAT.apiIGOPS}',
      ),
      CandyPost(
        name:  MediaCAT.nameDefaultValue,
        urlImage: MediaCAT.addressDefaultValue,
        url: MediaCAT.addressDefaultValue,
        isWeb: false,
        localName: MediaCAT.nameDefaultValue,
        isAvailable: false,
        collection: MediaCAT.adventurerGirlPlus,
        releaseDate: MediaCAT.dateDefaultValue,
        model: MediaCAT.modelDefaultValue,
        webUrl: MediaCAT.webAddressDefaultValue,
        previewUrl:MediaCAT.addressDefaultValue,
        previewName:  MediaCAT.nameDefaultValue,
        index_: 1,
        description: MediaCAT.descriptionDefaultValue,
        IGTag: '${MediaCAT.urlIG}CwBIKcrJUiR${MediaCAT.apiIGOPS}',
      ),
      CandyPost(
        name:  MediaCAT.nameDefaultValue,
        urlImage: MediaCAT.addressDefaultValue,
        url: MediaCAT.addressDefaultValue,
        isWeb: false,
        localName: MediaCAT.nameDefaultValue,
        isAvailable: false,
        collection: MediaCAT.adventurerGirlPlus,
        releaseDate: MediaCAT.dateDefaultValue,
        model: MediaCAT.modelDefaultValue,
        webUrl: MediaCAT.webAddressDefaultValue,
        previewUrl:MediaCAT.addressDefaultValue,
        previewName:  MediaCAT.nameDefaultValue,
        index_: 1,
        description: MediaCAT.descriptionDefaultValue,
        IGTag: '${MediaCAT.urlIG}CxI9MNeAt5m${MediaCAT.apiIGOPS}',
      ),
      CandyPost(
        name:  MediaCAT.nameDefaultValue,
        urlImage: MediaCAT.addressDefaultValue,
        url: MediaCAT.addressDefaultValue,
        isWeb: false,
        localName: MediaCAT.nameDefaultValue,
        isAvailable: false,
        collection: MediaCAT.adventurerGirlPlus,
        releaseDate: MediaCAT.dateDefaultValue,
        model: MediaCAT.modelDefaultValue,
        webUrl: MediaCAT.webAddressDefaultValue,
        previewUrl:MediaCAT.addressDefaultValue,
        previewName:  MediaCAT.nameDefaultValue,
        index_: 1,
        description: MediaCAT.descriptionDefaultValue,
        IGTag: '${MediaCAT.urlIG}CyOvps8Rg9D${MediaCAT.apiIGOPS}',
      ),
      CandyPost(
        name:  MediaCAT.nameDefaultValue,
        urlImage: MediaCAT.addressDefaultValue,
        url: MediaCAT.addressDefaultValue,
        isWeb: false,
        localName: MediaCAT.nameDefaultValue,
        isAvailable: false,
        collection: MediaCAT.adventurerGirlPlus,
        releaseDate: MediaCAT.dateDefaultValue,
        model: MediaCAT.modelDefaultValue,
        webUrl: MediaCAT.webAddressDefaultValue,
        previewUrl:MediaCAT.addressDefaultValue,
        previewName:  MediaCAT.nameDefaultValue,
        index_: 1,
        description: MediaCAT.descriptionDefaultValue,
        IGTag: '${MediaCAT.urlIG}Cwt2q-cs06T${MediaCAT.apiIGOPS}',
      ),

    ]
  );